numbers = ['3','5','7','9','10.5']
print(numbers)
numbers.append('python')
count = len(numbers)
print(count)
print(numbers[0])
print(numbers[-1])
print(numbers[1:5])
numbers.remove(numbers[-1])
print(numbers)
